### ISSUE TITLE
Bug on step 5

### ISSUE THREAD

**Issue by BDHiv** [jaxio/celerio-angular-quickstart#13]
running command:
**mvn spring-boot:run -e**

![image](https://cloud.githubusercontent.com/assets/6011475/20550416/2fb591ae-b114-11e6-8d49-852db2e04e44.png)

greetings from chile

**Comment by nromanetti** [comment]
Command must be run in the quickstart folder, not in quickstart/src folder.
Anyway, looks like maven only looks in your local repo, are you running in offline mode ?
