### ISSUE TITLE
Generated toString() method of Pk class references invalid LocalDateTime.getTime()

### ISSUE THREAD

**Issue by jdanosborne** [jaxio/celerio-angular-quickstart#17]
I have a table with a datetime column as part of the pk and the generated class's toString() method has...

if (isSailingDateSet()) {
            result.append(getSailingDate().getTime());
}

which leads to an error...

[ERROR] symbol:   method getTime()
[ERROR] location: class java.time.LocalDateTime

Perhaps this could just omit the getTime()?

This is my only remaining issue so I'll work around them for now and see how the runtime goes.

Dan

**Comment by nromanetti** [comment]
Which toString() ? the one from the PK class ?
If yes, please make sure that you are using the latest templates (git pull).... as this should have been fixed: check this commit (line 151 at the top):
https://github.com/jaxio/celerio-angular-quickstart/commit/143d0941fef6fb5a909b53f706e16a8070498283#diff-e1c404f0e6faba491162207bac7dd1f2L151

**Comment by jdanosborne** [comment]
Yes that one - and just my bad as I hadn't picked up the latest version. Sorted now.
