### ISSUE TITLE
How to restrict generate-sources

### ISSUE THREAD

**Issue by jdanosborne** [jaxio/celerio-angular-quickstart#19]
Is it possible to restrict the tables that get processed when reversing a schema? Or would the best approach be simply to edit the generated metada.xml file to remove the unwanted tables?

TIA

Dan

**Comment by nromanetti** [comment]
check the celerio-maven-plugin.xml file... you can exclude some tables in the generation phase (tables are reversed but celerio do not use them at generation phase)... 

        
        <tables>
            
            <table include="false" pattern="jhi_persistent_*"/>
        </tables>

If you want to also not reverse some tables, you can configure it in the pom.xml
check the end of this page: http://www.jaxio.com/documentation/celerio/extraction.html
look for jdbcTableNamePatterns

**Comment by jdanosborne** [comment]
That's perfect - many thanks
