### ISSUE TITLE
Errors after session expiry

### ISSUE THREAD

**Issue by jdanosborne** [jaxio/celerio-angular-quickstart#20]
If while searching/listing entities the session expires due to inactivity a request to http://localhost:8080/login is made according to Chrome Dev Tools but this page is not displayed (only seen in the Network tab), Console shows...
```
gnOperator.service.ts:82 JSON content could not be parsed
    GnOperatorService.handleError @ gnOperator.service.ts:82
    CatchSubscriber.error @ catch.ts:55
    MapSubscriber._next @ map.ts:77
    Subscriber.next @ Subscriber.ts:95
    onLoad @ http.umd.js:1168
    ZoneDelegate.invokeTask @ zone.js:275
    onInvokeTask @ core.umd.js:4382
    ZoneDelegate.invokeTask @ zone.js:274
    Zone.runTask @ zone.js:151
    ZoneTask.invoke @ zone.js:345

message.service.ts:25 ERROR: Could not get the results DETAIL: JSON content could not be parsed
```
The website is still on e.g. http://localhost:8080/gnOperator-list and to continue I have to explicitly log out and back in.

Might this be due in some way to my earlier report on ts compilation problems?

**Comment by nromanetti** [comment]
Fixed, could you please test it again?

**Comment by jdanosborne** [comment]
Yes, looks good now - thanks.
