### ISSUE TITLE
Cannot read property "" of undefined in case of nullable relation

### ISSUE THREAD

**Issue by achablowski** [jaxio/celerio-angular-quickstart#21]
Hello,

I'm trying to use your framework but I have a big problem with the grid included into the generated "template-list"
Example : 
The Car entity has an optional relation with Color entity, and I want to display a "Color column" in my grid.
If the relation is null, then I get a javascript error "Cannot read property "color" of undefined". I would like to have an empty value or a default value for the column, is it possible ? 
I tried to change the configuration into celerio-maven-plugin.xml but impossible to find any solution.

Best Regards

**Comment by nromanetti** [comment]
good catch BTW... thanks 👍
