### ISSUE TITLE
OneToOne Relation bidirectional not display

### ISSUE THREAD

**Issue by achablowski** [jaxio/celerio-angular-quickstart#24]
Hi,

I have a OneToOne bidirectional. but the relation only appears on the side with the column.
The entity is generated properly, with the annotation @OneToOne but the template doesn't generate attribute in entity-detail for this one.

Do you have a solution or a fix ? I wanted to display the relation with "Go To" button in both side.

Thanks

**Comment by achablowski** [comment]
`#foreach($attr in $entity.formAttributes.flatUp.list)
#if ($attr.isSimplePk() && !$attr.jpa.isManuallyAssigned())
## no need to display it...
#elseif($attr.isSimpleFk())
#xToOneEdit($attr.getXToOneRelation())`

the macro "xToOneEdit" isn't called on the entity mappedBy

**Comment by nromanetti** [comment]
fixed + provide an example (with user and passport tables)
