### ISSUE TITLE
Customising the UI

### ISSUE THREAD

**Issue by jdanosborne** [jaxio/celerio-angular-quickstart#29]
The basics are in place and I'm now considering some simple customisation. Do you have any pointers over how to avoid the over-writing of any customisations by subsequent re-generation of the sources? Is it simply a matter of re-applying any customisations with the help of source control?

I'm also wondering whether errors as raised in https://github.com/jaxio/celerio-angular-quickstart/issues/16#issuecomment-271977077 are likely to cause problems - has this issue been fixed yet?

Thanks for a great product!

**Comment by nromanetti** [comment]
As long as you can, you should modify the code generation templates.
But at one point manual customization in the generated code is necessary.

Celerio, the code generator, when it detects a manual modification, generates the file in a different folder you may use tools such as araxis merge or win merge to select the generated code snippet that you want.

You may find some useful info here:
http://www.jaxio.com/documentation/celerio/modification.html
in particular:
http://www.jaxio.com/documentation/celerio/modification.html#collisions-and-merging

**Comment by jdanosborne** [comment]
Thank you - that sounds promising.
