### ISSUE TITLE
travis: make chrome work

### ISSUE THREAD

**Issue by nromanetti** [jaxio/celerio-angular-quickstart#30]
we need chrome to start when doing CI with travis

**Comment by jeanlouisboudart** [comment]
According to the following website, this can be configured in karma.conf.js : 
http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/

**Comment by jeanlouisboudart** [comment]
The no sandbox option seems to be already generated by angular cli. 
I installe chrome and configured travis ci to use it. Builds is now green with karma tests enabled !
