### ISSUE TITLE
ran into issue with font-awsome and running ng-serve

### ISSUE THREAD

**Issue by saurabh0683** [jaxio/celerio-angular-quickstart#32]
**npm install --save font-awesome**
1 error Darwin 16.4.0
32 error argv "/usr/local/Cellar/node/7.7.1/bin/node" "/usr/local/bin/npm" "install" "--save" "font-awesom"
33 error node v7.7.1
34 error npm  v4.1.2
35 error code E404
36 error 404 Registry returned 404 for GET on https://registry.npmjs.org/font-awesom
37 error 404
38 error 404 'font-awesom' is not in the npm registry.
39 error 404 You should bug the author to publish it (or use the name yourself!)
40 error 404 Note that you can also install from a
41 error 404 tarball, folder, http url, or git url.
42 verbose exit [ 1, true ]

error while running server:
**ng serve --proxy-config proxy.conf.json**

ERROR in ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./src/styles.css
Module not found: Error: Can't resolve '@angular/material/core/theming/prebuilt/deeppurple-amber.css' in '/Users/saurabh/work/samples/angular_quickstart/celerio-angular-quickstart/quickstart/web/src'
 @ ./~/css-loader?{"sourceMap":false,"importLoaders":1}!./~/postcss-loader!./src/styles.css 3:10-201
 @ ./src/styles.css
 @ multi ./src/styles.css

**Comment by nromanetti** [comment]
Thanks for reporting it. I have freezed some version and it should be ok now.
