### ISSUE TITLE
Oracle table user doesnot exist

### ISSUE THREAD

**Issue by panksoni** [jaxio/celerio-angular-quickstart#33]
While reverse engineering my oracle database, getting error angular-quickstart: The table named USER could not be found.

In Oracle I cannot create a table named as user. I tried creating different table as account but did not work.

**Comment by nromanetti** [comment]
I guess that you haven't changed the configuration file [celerio-maven-plugin.xml](https://github.com/jaxio/celerio-angular-quickstart/blob/master/quickstart-conf/celerio-maven-plugin.xml) ... if it still mentions the USER table, then Celerio complains when it can't find it during the reverse phase.
Please let me know, you may provide your console output, it would help diagnose... :)

**Comment by panksoni** [comment]
Thanks that worked
