### ISSUE TITLE
Test case Issue

### ISSUE THREAD

**Issue by praveenrajkr** [jaxio/celerio-angular-quickstart#34]
Hi i am trying to create VM files for writing test cases foe all entity but i was unable to create files inside "src\test\java" is there any tutorial are guides available for generation of test cases

**Comment by nromanetti** [comment]
you may check this template out: 
https://github.com/jaxio/celerio-angular-quickstart/blob/master/pack-angular/celerio/pack-angular/src/test/java/ApplicationTests.java.p.vm

The file is generated in src/test/generated-java

More template examples here:
https://github.com/jaxio/pack-backend-jpa/tree/master/src/main/resources/celerio/pack-backend-jpa/src/test/java

The doc for templates is here:
http://www.jaxio.com/documentation/celerio/templates.html
