### ISSUE TITLE
project package

### ISSUE THREAD

**Issue by denizque** [jaxio/celerio-angular-quickstart#43]
By default the generated app comes as "com.mycompany.myapp"
Is there is specific configuration to be set so that it comes with the intended name, if so where?

**Comment by nromanetti** [comment]
you may configure it in [https://github.com/jaxio/celerio-angular-quickstart/blob/master/quickstart-conf/celerio-maven-plugin.xml](https://github.com/jaxio/celerio-angular-quickstart/blob/master/quickstart-conf/celerio-maven-plugin.xml)
