### ISSUE TITLE
Export .war issue

### ISSUE THREAD

**Issue by denizque** [jaxio/celerio-angular-quickstart#44]
When I export the generated app as .jar and run it, it works fine.
If I edit the pom file and change packaging to war: 

`<packaging>war</packaging>`

Then when I deploy the generated .war to the webserver it does't work.
Is there another setting which I'm missing?

**Comment by nromanetti** [comment]
We target jar application, not war... it won't work out of the box like that... currently we do not support it.

**Comment by denizque** [comment]
Thanks for your reply.
I see. Basically that's the idea behind SpringBoot.
The expectation (habit) immediately comes for ".war" file but SpringBoot has gone way more and simplified things :) Therefore you're right, war support is not even needed.

For others who might be unaware  of this issue (as I was) I'm providing the reference for clarification;

[](https://spring.io/blog/2014/03/07/deploying-spring-boot-applications)
