### ISSUE TITLE
How do you change the detault from port 8080

### ISSUE THREAD

**Issue by smartyme** [jaxio/celerio-angular-quickstart#45]

**Comment by nromanetti** [comment]
nothing magic, the generated backend code is using springboot (I encourage you to read the springboot doc). The port is configured in the properties file. You may change the template file so all the projets you generate get exactly the port you want
see here:
https://github.com/jaxio/celerio-angular-quickstart/blob/master/pack-angular/celerio/pack-angular/src/main/resources/application.yml.p.vm

or you may once the code is generated change the generated  properties file, which is for example:
https://github.com/jaxio/celerio-angular-quickstart/blob/master/quickstart-generated/src/main/resources/application.yml
