### ISSUE TITLE
Route Reload

### ISSUE THREAD

**Issue by youpage** [jaxio/celerio-angular-quickstart#8]
Hi,
On app route reload or direct link to an app route I get:

```
Whitelabel Error Page
There was an unexpected error (type=Not Found, status=404).
No message available
```

Is there a way to make it work?
With Apache and AngularJS we used .htaccess RewriteRule to overcome this issue.
Is there a way for Spring Boot to do similar?

**Comment by nromanetti** [comment]
It is now fixed... check the commit, it worths it
https://github.com/jaxio/celerio-angular-quickstart/commit/fdaeba15b8c76bd8997cfecf2f3e9d0c7a67297e

To my surprise reload not only loads the index but also the current view.

**Comment by youpage** [comment]
Hi Nicolas, thank you for the quick turn around. Works great. For my point of view this was the only missing thing, other than that great projects. GZ
