### ISSUE TITLE
Bug in Template EntityDTOService.java.e.vm

### ISSUE THREAD

**Issue by vivienmast** [jaxio/celerio-angular-quickstart#9]
There appears to be a bug in the Template EntityDTOService.java.e.vm, in line 192:

The variable declaration
`final int fdepth = depth;`
is within a for-loop:
`#foreach ($relation in $entity.manyToMany.list)`
This leads to the same variable being declared multiple times if several relations exist, causing a compile error.

Taking the declaration out of the loop solved the issue for me (though it would be prettier to surround it with an if-statement)

**Comment by nromanetti** [comment]
Good catch, thank you Vivien :)
Next time do not hesitate to create a pull request.

**Comment by vivienmast** [comment]
I was in the middle of something else when this came up, so I just dumped it here so that it wouldn't be forgotten. 
Next time I'll do it via pull request.
